apiVersion: v1
kind: Service
metadata:
  name: nfshome
  labels:
    app: nfshome
spec:
  ports:
  - name: portmapper-udp
    port: 111
    protocol: UDP
  - name: portmapper-tcp
    port: 111
    protocol: TCP
  - name: nfs-udp
    port: 2049
    protocol: UDP
  - name: nfs-tcp
    port: 2049
    protocol: TCP
  - name: mountd-udp
    port: 32767
    protocol: UDP
  - name: mountd-tcp
    port: 32767
    protocol: TCP
  selector:
    app: nfshome
