apiVersion: v1
kind: Service
metadata:
  name: nfshome
  labels:
    app: nfshome
spec:
  ports:
  - name: rpc
    port: 111
    protocol: UDP
  - name: nfs
    port: 2049
    protocol: TCP
  selector:
    app: nfshome
