apiVersion: v1
kind: ReplicationController
metadata:
  name: nfsopt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nfsopt
    spec:
      containers:
      - name: nfsopt
        image: wtakase/nfs-server:v3
        args:
        - /exports
        ports:
        - containerPort: 111
          protocol: UDP
        - containerPort: 111
          protocol: TCP
        - containerPort: 2049
          protocol: UDP
        - containerPort: 2049
          protocol: TCP
        - containerPort: 32765
          protocol: UDP
        - containerPort: 32765
          protocol: TCP
        - containerPort: 32766
          protocol: UDP
        - containerPort: 32766
          protocol: TCP
        - containerPort: 32767
          protocol: UDP
        - containerPort: 32767
          protocol: TCP
        - containerPort: 32768
          protocol: UDP
        - containerPort: 32768
          protocol: TCP
        securityContext:
          privileged: true
